### ISSUE TITLE
ID not got when using mongoose debug

### ISSUE THREAD

**Issue by gpradeepjain** [puzpuzpuz/cls-rtracer#23]
I am using mongoose like below

```
require('mongoose').set('debug', function (collectionName, method, query, options) {
  logger.info(`db.${collectionName}.${method}(${JSON.stringify(query)}, ${JSON.stringify(options)});`);
});

```
I have configured my logger to append rTracer.id() when ever its found, above does never get the ID. even though its a http request.

**Comment by puzpuzpuz** [comment]
I didn't check Mongoose, but most likely that the debug callback is being executed somewhere at the native mongodb driver level, which doesn't play well with Async Hooks API (by integrating with Embedder API).

If that's possible, you should try to change your code so that the debug logging happens as a part of running your query. If that's not possible, I advice you to create a GH issue against `mongoose`/`node-mongodb-native`.

**Comment by aigoncharov** [comment]
Here's the open issue in mongoose repo https://github.com/Automattic/mongoose/issues/3313

**Comment by gpradeepjain** [comment]
So as of now there is no solution for same?

**Comment by puzpuzpuz** [comment]
I'm afraid, not (or, at least I'm not aware of it). This issue has to be resolved on `mongoose`/`node-mongodb-native` side.

Closing this issue because of that.
